#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AutoParts")]
	public partial class autopartsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertparts(parts instance);
    partial void Updateparts(parts instance);
    partial void Deleteparts(parts instance);
    partial void Insertproviders(providers instance);
    partial void Updateproviders(providers instance);
    partial void Deleteproviders(providers instance);
    #endregion
		
		public autopartsDataContext() : 
				base(global::DB.Properties.Settings.Default.AutoPartsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public autopartsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public autopartsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public autopartsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public autopartsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bridge_providers_parts> bridge_providers_parts
		{
			get
			{
				return this.GetTable<bridge_providers_parts>();
			}
		}
		
		public System.Data.Linq.Table<deals> deals
		{
			get
			{
				return this.GetTable<deals>();
			}
		}
		
		public System.Data.Linq.Table<parts> parts
		{
			get
			{
				return this.GetTable<parts>();
			}
		}
		
		public System.Data.Linq.Table<priceHistory> priceHistory
		{
			get
			{
				return this.GetTable<priceHistory>();
			}
		}
		
		public System.Data.Linq.Table<providers> providers
		{
			get
			{
				return this.GetTable<providers>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bridge_providers_parts")]
	public partial class bridge_providers_parts
	{
		
		private string _providers_title;
		
		private int _parts_article;
		
		public bridge_providers_parts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_providers_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string providers_title
		{
			get
			{
				return this._providers_title;
			}
			set
			{
				if ((this._providers_title != value))
				{
					this._providers_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parts_article", DbType="Int NOT NULL")]
		public int parts_article
		{
			get
			{
				return this._parts_article;
			}
			set
			{
				if ((this._parts_article != value))
				{
					this._parts_article = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.deals")]
	public partial class deals
	{
		
		private System.DateTime _deal_date;
		
		private int _parts_article;
		
		private int _deal_parts_count;
		
		public deals()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deal_date", DbType="Date NOT NULL")]
		public System.DateTime deal_date
		{
			get
			{
				return this._deal_date;
			}
			set
			{
				if ((this._deal_date != value))
				{
					this._deal_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parts_article", DbType="Int NOT NULL")]
		public int parts_article
		{
			get
			{
				return this._parts_article;
			}
			set
			{
				if ((this._parts_article != value))
				{
					this._parts_article = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deal_parts_count", DbType="Int NOT NULL")]
		public int deal_parts_count
		{
			get
			{
				return this._deal_parts_count;
			}
			set
			{
				if ((this._deal_parts_count != value))
				{
					this._deal_parts_count = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parts")]
	public partial class parts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _title;
		
		private int _article;
		
		private string _manufacturer;
		
		private int _price;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnarticleChanging(int value);
    partial void OnarticleChanged();
    partial void OnmanufacturerChanging(string value);
    partial void OnmanufacturerChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    #endregion
		
		public parts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_article", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int article
		{
			get
			{
				return this._article;
			}
			set
			{
				if ((this._article != value))
				{
					this.OnarticleChanging(value);
					this.SendPropertyChanging();
					this._article = value;
					this.SendPropertyChanged("article");
					this.OnarticleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufacturer", DbType="NVarChar(50)")]
		public string manufacturer
		{
			get
			{
				return this._manufacturer;
			}
			set
			{
				if ((this._manufacturer != value))
				{
					this.OnmanufacturerChanging(value);
					this.SendPropertyChanging();
					this._manufacturer = value;
					this.SendPropertyChanged("manufacturer");
					this.OnmanufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
		public int price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.priceHistory")]
	public partial class priceHistory
	{
		
		private int _parts_article;
		
		private System.DateTime _price_date;
		
		private int _price;
		
		public priceHistory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parts_article", DbType="Int NOT NULL")]
		public int parts_article
		{
			get
			{
				return this._parts_article;
			}
			set
			{
				if ((this._parts_article != value))
				{
					this._parts_article = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_date", DbType="Date NOT NULL")]
		public System.DateTime price_date
		{
			get
			{
				return this._price_date;
			}
			set
			{
				if ((this._price_date != value))
				{
					this._price_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
		public int price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.providers")]
	public partial class providers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _title;
		
		private string _provider_address;
		
		private string _phone;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onprovider_addressChanging(string value);
    partial void Onprovider_addressChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public providers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provider_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string provider_address
		{
			get
			{
				return this._provider_address;
			}
			set
			{
				if ((this._provider_address != value))
				{
					this.Onprovider_addressChanging(value);
					this.SendPropertyChanging();
					this._provider_address = value;
					this.SendPropertyChanged("provider_address");
					this.Onprovider_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(12)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
